//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R: Sendable {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: One noun, every day, forever.
      ///
      /// Key: widget_description
      var widget_description: RswiftResources.StringResource { .init(key: "widget_description", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Everyday Noun
      ///
      /// Key: widget_display_name
      var widget_display_name: RswiftResources.StringResource { .init(key: "widget_display_name", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `WidgetBackground`.
    var widgetBackground: RswiftResources.ColorResource { .init(name: "WidgetBackground", path: [], bundle: bundle) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var nsExtension: nsExtension { .init(bundle: bundle) }

    func nsExtension(bundle: Foundation.Bundle) -> nsExtension {
      .init(bundle: bundle)
    }

    struct nsExtension {
      let bundle: Foundation.Bundle
      var _key: String { bundle.infoDictionaryString(path: ["NSExtension"], key: "_key") ?? "NSExtension" }
      var nsExtensionPointIdentifier: String { bundle.infoDictionaryString(path: ["NSExtension"], key: "NSExtensionPointIdentifier") ?? "com.apple.widgetkit-extension" }
    }
  }
}